language: common-lisp
sudo: false

install:
  # Clone trivial-exe
  - git clone https://github.com/ceramic/trivial-exe ~/lisp/trivial-exe

addons:
  apt:
    packages:
      - sbcl

script:
  - sbcl --noinform
         --eval '(ql:quickload :fiveam)'
         --eval '(setf fiveam:*debug-on-error* t
                       fiveam:*debug-on-failure* t)'
         --eval '(setf *debugger-hook*
                   (lambda (c h)
                     (declare (ignore h))
                     (uiop:print-condition-backtrace c)
                     (uiop:quit -1)))'
         --eval '(ql:quickload :trivial-build-test)'
         --eval '(trivial-build-test:run-tests)'

notifications:
  email:
    - eudoxiahp@gmail.com
