language: common-lisp
sudo: true

install:
  # Update
  - sudo apt-get update
  # Install SBCL
  - sudo apt-get install sbcl curl
  # Clone QL
  - curl -O https://beta.quicklisp.org/quicklisp.lisp
  # Install QL
  - sbcl --load quicklisp.lisp
         --eval '(quicklisp-quickstart:install)'
         --eval '(ql:add-to-init-file)'
  # Clone trivial-exe
  - git clone https://github.com/ceramic/trivial-exe ~/lisp/trivial-exe

script:
  - sbcl --noinform --disable-debugger
         --eval '(ql:quickload :fiveam)'
         --eval '(setf fiveam:*debug-on-error* t
                       fiveam:*debug-on-failure* t)'
         --eval '(setf *debugger-hook*
                   (lambda (c h)
                     (declare (ignore h))
                     (uiop:print-condition-backtrace c)
                     (uiop:quit -1)))'
         --eval '(ql:quickload :trivial-build-test)'
         --eval '(trivial-build-test:run-tests)'

notifications:
  email:
    - eudoxiahp@gmail.com
